import type { AffinityMetric, Drug, ReceptorAction, ReceptorBinding } from "./types";
import { normalizeBinding } from "./affinity";

/** Compact binding constructor — valueNm is the quantitative constant in nM. */
function b(
  receptorId: string,
  valueNm: number,
  metric: AffinityMetric,
  action: ReceptorAction,
  efficacy: number,
  note?: string,
  source = "literature-approx",
): ReceptorBinding {
  return normalizeBinding({ receptorId, valueNm, metric, action, efficacy, note, source });
}

const RAW_DRUGS: Drug[] = [
  // ——— Opioids ———
  {
    id: "morphine",
    name: "Morphine",
    aliases: ["MS Contin", "Roxanol"],
    class: "Opioid analgesic",
    category: "Pain",
    description: "Prototype μ-opioid full agonist for moderate–severe pain.",
    defaultDoseMg: 15,
    doseUnit: "mg",
    halfLifeHours: 3,
    freeConcNm: 25,
    bindings: [
      b("mu-opioid", 1.8, "Ki", "agonist", 1.0, "PDSP-range MOR Ki"),
      b("kappa-opioid", 46, "Ki", "agonist", 0.4),
      b("delta-opioid", 90, "Ki", "agonist", 0.5),
    ],
  },
  {
    id: "oxycodone",
    name: "Oxycodone",
    aliases: ["OxyContin", "Percocet"],
    class: "Opioid analgesic",
    category: "Pain",
    description: "Semi-synthetic μ-preferring opioid agonist.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 3.5,
    freeConcNm: 40,
    bindings: [
      b("mu-opioid", 18, "Ki", "agonist", 0.95),
      b("kappa-opioid", 950, "Ki", "agonist", 0.3),
      b("delta-opioid", 900, "Ki", "agonist", 0.35),
    ],
  },
  {
    id: "hydrocodone",
    name: "Hydrocodone",
    aliases: ["Vicodin", "Norco", "Lortab"],
    class: "Opioid analgesic",
    category: "Pain",
    description: "Common oral μ-opioid often co-formulated with acetaminophen.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 35,
    bindings: [
      b("mu-opioid", 41, "Ki", "agonist", 0.85),
      b("delta-opioid", 1200, "Ki", "agonist", 0.25),
    ],
  },
  {
    id: "hydromorphone",
    name: "Hydromorphone",
    aliases: ["Dilaudid"],
    class: "Opioid analgesic",
    category: "Pain",
    description: "Potent semi-synthetic μ-opioid agonist.",
    defaultDoseMg: 2,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 8,
    bindings: [
      b("mu-opioid", 0.6, "Ki", "agonist", 1.0),
      b("delta-opioid", 50, "Ki", "agonist", 0.35),
    ],
  },
  {
    id: "codeine",
    name: "Codeine",
    aliases: ["Tylenol #3"],
    class: "Opioid analgesic / antitussive",
    category: "Pain",
    description: "Prodrug opioid with weaker μ activity after CYP2D6 conversion.",
    defaultDoseMg: 30,
    doseUnit: "mg",
    halfLifeHours: 3,
    freeConcNm: 80,
    bindings: [
      b("mu-opioid", 650, "Ki", "agonist", 0.55, "Parent; morphine metabolite much tighter"),
    ],
  },
  {
    id: "tramadol",
    name: "Tramadol",
    aliases: ["Ultram"],
    class: "Atypical opioid",
    category: "Pain",
    description: "Weak μ agonist plus SERT/NET inhibition.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 400,
    bindings: [
      b("mu-opioid", 2100, "Ki", "partial-agonist", 0.35, "(+)-M1 metabolite ~10× tighter"),
      b("sert", 500, "Ki", "inhibitor", 0.7),
      b("net", 780, "Ki", "inhibitor", 0.6),
    ],
  },
  {
    id: "fentanyl",
    name: "Fentanyl",
    aliases: ["Duragesic", "Sublimaze"],
    class: "Synthetic opioid",
    category: "Pain",
    description: "High-potency μ-opioid full agonist.",
    defaultDoseMg: 0.1,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 3,
    bindings: [
      b("mu-opioid", 0.7, "Ki", "agonist", 1.0),
      b("delta-opioid", 150, "Ki", "agonist", 0.3),
    ],
  },
  {
    id: "methadone",
    name: "Methadone",
    aliases: ["Dolophine", "Methadose"],
    class: "Opioid agonist (long-acting)",
    category: "Pain",
    description: "Long-acting μ agonist used for OUD and chronic pain; also weak NMDA antagonist.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 30,
    freeConcNm: 80,
    bindings: [
      b("mu-opioid", 3.4, "Ki", "agonist", 0.95),
      b("nmda", 3700, "Ki", "antagonist", 0.35, "racemic mixture; (S)-enantiomer NMDA"),
      b("sert", 260, "Ki", "inhibitor", 0.25),
    ],
  },
  {
    id: "buprenorphine",
    name: "Buprenorphine",
    aliases: ["Subutex", "Suboxone", "Butrans"],
    class: "Partial opioid agonist",
    category: "Pain",
    description: "High-affinity μ partial agonist + κ antagonist; OUD and analgesia.",
    defaultDoseMg: 8,
    doseUnit: "mg",
    halfLifeHours: 32,
    freeConcNm: 5,
    bindings: [
      b("mu-opioid", 0.22, "Ki", "partial-agonist", 0.4, "Very high affinity, partial efficacy"),
      b("kappa-opioid", 0.11, "Ki", "antagonist", 0.9),
      b("delta-opioid", 1.2, "Ki", "antagonist", 0.5),
    ],
  },
  {
    id: "naloxone",
    name: "Naloxone",
    aliases: ["Narcan"],
    class: "Opioid antagonist",
    category: "Antidote",
    description: "Competitive μ-opioid antagonist for overdose reversal.",
    defaultDoseMg: 2,
    doseUnit: "mg",
    halfLifeHours: 1.5,
    freeConcNm: 20,
    bindings: [
      b("mu-opioid", 1.1, "Ki", "antagonist", 1.0),
      b("kappa-opioid", 5.5, "Ki", "antagonist", 0.9),
      b("delta-opioid", 16, "Ki", "antagonist", 0.85),
    ],
  },
  {
    id: "naltrexone",
    name: "Naltrexone",
    aliases: ["ReVia", "Vivitrol"],
    class: "Opioid antagonist",
    category: "Antidote",
    description: "Long-acting competitive opioid antagonist for OUD and alcohol use disorder.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 15,
    bindings: [
      b("mu-opioid", 0.34, "Ki", "antagonist", 1.0),
      b("kappa-opioid", 1.0, "Ki", "antagonist", 0.9),
      b("delta-opioid", 10, "Ki", "antagonist", 0.8),
    ],
  },

  // ——— Antidepressants / psych ———
  {
    id: "sertraline",
    name: "Sertraline",
    aliases: ["Zoloft"],
    class: "SSRI",
    category: "Psychiatric",
    description: "Selective serotonin reuptake inhibitor.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 26,
    freeConcNm: 15,
    bindings: [
      b("sert", 0.29, "Ki", "inhibitor", 0.95, "Human SERT"),
      b("dat", 25, "Ki", "inhibitor", 0.15),
      b("sigma1", 32, "Ki", "agonist", 0.4),
    ],
  },
  {
    id: "fluoxetine",
    name: "Fluoxetine",
    aliases: ["Prozac"],
    class: "SSRI",
    category: "Psychiatric",
    description: "Long-acting SSRI; strong CYP2D6 inhibitor.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 96,
    freeConcNm: 30,
    bindings: [
      b("sert", 0.81, "Ki", "inhibitor", 0.95),
      b("5ht2c", 72, "Ki", "antagonist", 0.4),
    ],
  },
  {
    id: "escitalopram",
    name: "Escitalopram",
    aliases: ["Lexapro"],
    class: "SSRI",
    category: "Psychiatric",
    description: "S-enantiomer of citalopram; highly selective SERT inhibitor.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 30,
    freeConcNm: 20,
    bindings: [
      b("sert", 1.1, "Ki", "inhibitor", 0.98),
      b("h1", 2000, "Ki", "antagonist", 0.05),
    ],
  },
  {
    id: "citalopram",
    name: "Citalopram",
    aliases: ["Celexa"],
    class: "SSRI",
    category: "Psychiatric",
    description: "Highly selective SERT inhibitor.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 35,
    freeConcNm: 40,
    bindings: [
      b("sert", 1.16, "Ki", "inhibitor", 0.95),
      b("h1", 370, "Ki", "antagonist", 0.15),
    ],
  },
  {
    id: "paroxetine",
    name: "Paroxetine",
    aliases: ["Paxil"],
    class: "SSRI",
    category: "Psychiatric",
    description: "Potent SSRI with mild anticholinergic and NET affinity.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 21,
    freeConcNm: 15,
    bindings: [
      b("sert", 0.07, "Ki", "inhibitor", 0.98),
      b("net", 40, "Ki", "inhibitor", 0.3),
      b("m1", 80, "Ki", "antagonist", 0.25),
    ],
  },
  {
    id: "venlafaxine",
    name: "Venlafaxine",
    aliases: ["Effexor"],
    class: "SNRI",
    category: "Psychiatric",
    description: "Serotonin–norepinephrine reuptake inhibitor.",
    defaultDoseMg: 75,
    doseUnit: "mg",
    halfLifeHours: 5,
    freeConcNm: 200,
    bindings: [
      b("sert", 82, "Ki", "inhibitor", 0.9, "Parent; desvenlafaxine also active"),
      b("net", 2480, "Ki", "inhibitor", 0.75),
    ],
  },
  {
    id: "duloxetine",
    name: "Duloxetine",
    aliases: ["Cymbalta"],
    class: "SNRI",
    category: "Psychiatric",
    description: "Balanced SNRI used for depression and neuropathic pain.",
    defaultDoseMg: 60,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 30,
    bindings: [
      b("sert", 0.8, "Ki", "inhibitor", 0.9),
      b("net", 7.5, "Ki", "inhibitor", 0.85),
    ],
  },
  {
    id: "bupropion",
    name: "Bupropion",
    aliases: ["Wellbutrin", "Zyban"],
    class: "NDRI",
    category: "Psychiatric",
    description: "Dopamine/norepinephrine reuptake inhibitor; smoking cessation aid.",
    defaultDoseMg: 150,
    doseUnit: "mg",
    halfLifeHours: 21,
    freeConcNm: 400,
    bindings: [
      b("dat", 520, "Ki", "inhibitor", 0.7),
      b("net", 52000, "Ki", "inhibitor", 0.65, "Weak; metabolites contribute"),
      b("nachr", 1400, "IC50", "antagonist", 0.45, "α3β4 / α4β2 nAChR IC50-range"),
    ],
  },
  {
    id: "mirtazapine",
    name: "Mirtazapine",
    aliases: ["Remeron"],
    class: "NaSSA",
    category: "Psychiatric",
    description: "α₂ and 5-HT₂/₃ antagonist; sedating antidepressant.",
    defaultDoseMg: 15,
    doseUnit: "mg",
    halfLifeHours: 30,
    freeConcNm: 50,
    bindings: [
      b("alpha2", 20, "Ki", "antagonist", 0.9),
      b("5ht2a", 69, "Ki", "antagonist", 0.9),
      b("5ht2c", 39, "Ki", "antagonist", 0.85),
      b("5ht3", 8, "Ki", "antagonist", 0.85),
      b("h1", 0.14, "Ki", "antagonist", 0.95),
    ],
  },
  {
    id: "trazodone",
    name: "Trazodone",
    aliases: ["Desyrel"],
    class: "SARI",
    category: "Psychiatric",
    description: "5-HT₂A antagonist with weak SERT inhibition; used for sleep.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 7,
    freeConcNm: 300,
    bindings: [
      b("5ht2a", 35.8, "Ki", "antagonist", 0.9),
      b("sert", 160, "Ki", "inhibitor", 0.4),
      b("h1", 220, "Ki", "antagonist", 0.7),
      b("alpha1", 42, "Ki", "antagonist", 0.65),
    ],
  },
  {
    id: "buspirone",
    name: "Buspirone",
    aliases: ["Buspar"],
    class: "Azapirone anxiolytic",
    category: "Psychiatric",
    description: "5-HT₁A partial agonist for GAD.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 15,
    bindings: [
      b("5ht1a", 20, "Ki", "partial-agonist", 0.55),
      b("d2", 240, "Ki", "antagonist", 0.3),
    ],
  },
  {
    id: "alprazolam",
    name: "Alprazolam",
    aliases: ["Xanax"],
    class: "Benzodiazepine",
    category: "Psychiatric",
    description: "Short-acting GABA-A positive allosteric modulator.",
    defaultDoseMg: 0.5,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 30,
    bindings: [
      b("gaba-a-bz", 3.4, "Ki", "modulator-positive", 0.95, "BZ site Ki"),
      b("gaba-a", 3.4, "Ki", "modulator-positive", 0.9),
    ],
  },
  {
    id: "diazepam",
    name: "Diazepam",
    aliases: ["Valium"],
    class: "Benzodiazepine",
    category: "Psychiatric",
    description: "Long-acting benzo for anxiety, spasms, alcohol withdrawal.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 48,
    freeConcNm: 50,
    bindings: [
      b("gaba-a-bz", 8.9, "Ki", "modulator-positive", 0.95),
      b("gaba-a", 8.9, "Ki", "modulator-positive", 0.9),
    ],
  },
  {
    id: "lorazepam",
    name: "Lorazepam",
    aliases: ["Ativan"],
    class: "Benzodiazepine",
    category: "Psychiatric",
    description: "Intermediate-acting benzo; common for acute anxiety and status.",
    defaultDoseMg: 1,
    doseUnit: "mg",
    halfLifeHours: 14,
    freeConcNm: 25,
    bindings: [
      b("gaba-a-bz", 2.0, "Ki", "modulator-positive", 0.95),
      b("gaba-a", 2.0, "Ki", "modulator-positive", 0.9),
    ],
  },
  {
    id: "clonazepam",
    name: "Clonazepam",
    aliases: ["Klonopin"],
    class: "Benzodiazepine",
    category: "Psychiatric",
    description: "Long-acting high-potency benzo for panic and seizures.",
    defaultDoseMg: 0.5,
    doseUnit: "mg",
    halfLifeHours: 30,
    freeConcNm: 15,
    bindings: [
      b("gaba-a-bz", 0.5, "Ki", "modulator-positive", 0.95),
      b("gaba-a", 0.5, "Ki", "modulator-positive", 0.9),
    ],
  },
  {
    id: "zolpidem",
    name: "Zolpidem",
    aliases: ["Ambien"],
    class: "Z-drug hypnotic",
    category: "Sleep",
    description: "α1-preferring GABA-A positive modulator for insomnia.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 40,
    bindings: [
      b("gaba-a-bz", 16, "Ki", "modulator-positive", 0.85, "α1-preferring"),
      b("gaba-a", 16, "Ki", "modulator-positive", 0.8),
    ],
  },
  {
    id: "risperidone",
    name: "Risperidone",
    aliases: ["Risperdal"],
    class: "Atypical antipsychotic",
    category: "Psychiatric",
    description: "D₂ / 5-HT₂A antagonist antipsychotic.",
    defaultDoseMg: 2,
    doseUnit: "mg",
    halfLifeHours: 20,
    freeConcNm: 8,
    bindings: [
      b("d2", 3.13, "Ki", "antagonist", 0.95),
      b("5ht2a", 0.17, "Ki", "antagonist", 0.95),
      b("alpha1", 2.3, "Ki", "antagonist", 0.7),
      b("h1", 20, "Ki", "antagonist", 0.5),
    ],
  },
  {
    id: "quetiapine",
    name: "Quetiapine",
    aliases: ["Seroquel"],
    class: "Atypical antipsychotic",
    category: "Psychiatric",
    description: "Multi-receptor antagonist; sedating at low dose.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 7,
    freeConcNm: 100,
    bindings: [
      b("h1", 6.9, "Ki", "antagonist", 0.95),
      b("5ht2a", 101, "Ki", "antagonist", 0.8),
      b("d2", 380, "Ki", "antagonist", 0.55),
      b("alpha1", 22, "Ki", "antagonist", 0.75),
      b("m1", 1200, "Ki", "antagonist", 0.35),
    ],
  },
  {
    id: "olanzapine",
    name: "Olanzapine",
    aliases: ["Zyprexa"],
    class: "Atypical antipsychotic",
    category: "Psychiatric",
    description: "Multi-receptor antagonist with strong H₁/M₁ affinity.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 30,
    freeConcNm: 20,
    bindings: [
      b("d2", 20, "Ki", "antagonist", 0.85),
      b("5ht2a", 4, "Ki", "antagonist", 0.95),
      b("h1", 0.1, "Ki", "antagonist", 0.98),
      b("m1", 2.5, "Ki", "antagonist", 0.8),
      b("alpha1", 19, "Ki", "antagonist", 0.7),
    ],
  },
  {
    id: "aripiprazole",
    name: "Aripiprazole",
    aliases: ["Abilify"],
    class: "Atypical antipsychotic",
    category: "Psychiatric",
    description: "D₂ / 5-HT₁A partial agonist antipsychotic (stabilizer profile).",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 75,
    freeConcNm: 15,
    bindings: [
      b("d2", 0.34, "Ki", "partial-agonist", 0.25, "Partial agonist ~25–30% efficacy"),
      b("5ht1a", 1.7, "Ki", "partial-agonist", 0.5),
      b("5ht2a", 3.4, "Ki", "antagonist", 0.7),
    ],
  },
  {
    id: "haloperidol",
    name: "Haloperidol",
    aliases: ["Haldol"],
    class: "Typical antipsychotic",
    category: "Psychiatric",
    description: "High-potency D₂ antagonist first-generation antipsychotic.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 20,
    freeConcNm: 5,
    bindings: [
      b("d2", 0.7, "Ki", "antagonist", 0.98),
      b("d1", 80, "Ki", "antagonist", 0.4),
      b("5ht2a", 45, "Ki", "antagonist", 0.5),
      b("alpha1", 12, "Ki", "antagonist", 0.5),
    ],
  },

  // ——— Stimulants ———
  {
    id: "amphetamine",
    name: "Amphetamine",
    aliases: ["Adderall", "dextroamphetamine"],
    class: "Stimulant",
    category: "ADHD",
    description: "Monoamine releaser via DAT/NET/VMAT2 and TAAR1.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 10,
    freeConcNm: 80,
    bindings: [
      b("dat", 34, "Ki", "releaser", 0.95, "d-amphetamine DAT Ki-range"),
      b("net", 39, "Ki", "releaser", 0.9),
      b("vmat2", 2000, "IC50", "inhibitor", 0.85),
      b("taar1", 1000, "EC50", "agonist", 0.8, "Approximate human TAAR1 EC50"),
      b("sert", 3830, "Ki", "releaser", 0.3),
    ],
  },
  {
    id: "methylphenidate",
    name: "Methylphenidate",
    aliases: ["Ritalin", "Concerta"],
    class: "Stimulant",
    category: "ADHD",
    description: "DAT/NET reuptake inhibitor (not releaser).",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 3.5,
    freeConcNm: 40,
    bindings: [
      b("dat", 34, "Ki", "inhibitor", 0.9),
      b("net", 339, "Ki", "inhibitor", 0.65),
    ],
  },
  {
    id: "lisdexamfetamine",
    name: "Lisdexamfetamine",
    aliases: ["Vyvanse"],
    class: "Stimulant prodrug",
    category: "ADHD",
    description: "Prodrug of d-amphetamine; smoother monoamine release profile.",
    defaultDoseMg: 30,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 60,
    bindings: [
      b("dat", 34, "Ki", "releaser", 0.9, "Active d-amphetamine after conversion"),
      b("net", 39, "Ki", "releaser", 0.85),
      b("vmat2", 2000, "IC50", "inhibitor", 0.8),
    ],
  },
  {
    id: "atomoxetine",
    name: "Atomoxetine",
    aliases: ["Strattera"],
    class: "NRI",
    category: "ADHD",
    description: "Selective norepinephrine reuptake inhibitor.",
    defaultDoseMg: 40,
    doseUnit: "mg",
    halfLifeHours: 5,
    freeConcNm: 50,
    bindings: [b("net", 5, "Ki", "inhibitor", 0.95)],
  },
  {
    id: "modafinil",
    name: "Modafinil",
    aliases: ["Provigil"],
    class: "Eugeroic",
    category: "ADHD",
    description: "Wake-promoting agent with weak DAT affinity.",
    defaultDoseMg: 200,
    doseUnit: "mg",
    halfLifeHours: 15,
    freeConcNm: 5000,
    bindings: [b("dat", 3700, "Ki", "inhibitor", 0.35, "Weak DAT occupancy at clinical doses")],
  },
  {
    id: "caffeine",
    name: "Caffeine",
    aliases: ["coffee", "tea"],
    class: "Methylxanthine",
    category: "Stimulant",
    description: "Adenosine A₁/A₂A antagonist; everyday stimulant.",
    defaultDoseMg: 100,
    doseUnit: "mg",
    halfLifeHours: 5,
    freeConcNm: 20000,
    bindings: [
      b("a1", 12000, "Ki", "antagonist", 0.85),
      b("a2a", 2300, "Ki", "antagonist", 0.9),
    ],
  },
  {
    id: "theophylline",
    name: "Theophylline",
    aliases: ["Theo-Dur"],
    class: "Methylxanthine",
    category: "Respiratory",
    description: "Adenosine antagonist and PDE inhibitor for asthma/COPD.",
    defaultDoseMg: 200,
    doseUnit: "mg",
    halfLifeHours: 8,
    freeConcNm: 40000,
    bindings: [
      b("a1", 9000, "Ki", "antagonist", 0.8),
      b("a2a", 25000, "Ki", "antagonist", 0.8),
    ],
  },
  {
    id: "nicotine",
    name: "Nicotine",
    aliases: ["nicotine patch", "nicotine gum"],
    class: "nAChR agonist",
    category: "Stimulant",
    description: "Agonist at nicotinic acetylcholine receptors.",
    defaultDoseMg: 4,
    doseUnit: "mg",
    halfLifeHours: 2,
    freeConcNm: 50,
    bindings: [b("nachr", 1.0, "Ki", "agonist", 0.9, "α4β2 high-affinity site")],
  },
  {
    id: "varenicline",
    name: "Varenicline",
    aliases: ["Chantix", "Champix"],
    class: "nAChR partial agonist",
    category: "Stimulant",
    description: "α4β2 nAChR partial agonist for smoking cessation.",
    defaultDoseMg: 1,
    doseUnit: "mg",
    halfLifeHours: 24,
    freeConcNm: 10,
    bindings: [
      b("nachr", 0.15, "Ki", "partial-agonist", 0.45, "α4β2 partial agonist"),
    ],
  },
  {
    id: "ethanol",
    name: "Ethanol",
    aliases: ["alcohol", "EtOH"],
    class: "CNS depressant",
    category: "Other",
    description: "Positive GABA-A modulator and NMDA antagonist.",
    defaultDoseMg: 14000,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 10000000,
    bindings: [
      b("gaba-a", 10000000, "EC50", "modulator-positive", 0.7, "mM-range; educational proxy"),
      b("nmda", 50000000, "IC50", "antagonist", 0.55),
    ],
  },

  // ——— Allergy / GI ———
  {
    id: "diphenhydramine",
    name: "Diphenhydramine",
    aliases: ["Benadryl"],
    class: "1st-gen antihistamine",
    category: "Allergy",
    description: "H₁ antagonist with strong muscarinic and sedative effects.",
    defaultDoseMg: 25,
    doseUnit: "mg",
    halfLifeHours: 8,
    freeConcNm: 80,
    bindings: [
      b("h1", 9.6, "Ki", "antagonist", 0.95),
      b("m1", 80, "Ki", "antagonist", 0.75),
      b("m2", 120, "Ki", "antagonist", 0.7),
      b("m3", 100, "Ki", "antagonist", 0.7),
      b("sert", 1100, "Ki", "inhibitor", 0.2),
    ],
  },
  {
    id: "loratadine",
    name: "Loratadine",
    aliases: ["Claritin"],
    class: "2nd-gen antihistamine",
    category: "Allergy",
    description: "Peripheral H₁ antagonist; low CNS penetration.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 8,
    freeConcNm: 5,
    bindings: [b("h1", 35, "Ki", "antagonist", 0.9)],
  },
  {
    id: "cetirizine",
    name: "Cetirizine",
    aliases: ["Zyrtec"],
    class: "2nd-gen antihistamine",
    category: "Allergy",
    description: "Selective H₁ antagonist.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 8,
    freeConcNm: 30,
    bindings: [b("h1", 6, "Ki", "antagonist", 0.92)],
  },
  {
    id: "hydroxyzine",
    name: "Hydroxyzine",
    aliases: ["Vistaril", "Atarax"],
    class: "1st-gen antihistamine",
    category: "Allergy",
    description: "H₁ antagonist used for itch, anxiety, and sedation.",
    defaultDoseMg: 25,
    doseUnit: "mg",
    halfLifeHours: 20,
    freeConcNm: 40,
    bindings: [
      b("h1", 2, "Ki", "antagonist", 0.95),
      b("5ht2a", 50, "Ki", "antagonist", 0.4),
    ],
  },
  {
    id: "famotidine",
    name: "Famotidine",
    aliases: ["Pepcid"],
    class: "H₂ blocker",
    category: "GI",
    description: "H₂ antagonist reducing gastric acid.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 3,
    freeConcNm: 50,
    bindings: [b("h2", 17, "Ki", "antagonist", 0.95)],
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    aliases: ["Prilosec"],
    class: "PPI",
    category: "GI",
    description: "Proton pump inhibitor (included as enzyme target proxy).",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 1,
    freeConcNm: 200,
    bindings: [
      b("h2", 5000, "IC50", "antagonist", 0.1, "Indirect acid suppression via H+/K+-ATPase"),
    ],
  },
  {
    id: "ondansetron",
    name: "Ondansetron",
    aliases: ["Zofran"],
    class: "5-HT₃ antagonist",
    category: "GI",
    description: "Antiemetic via 5-HT₃ blockade.",
    defaultDoseMg: 8,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 20,
    bindings: [b("5ht3", 6.1, "Ki", "antagonist", 0.98)],
  },
  {
    id: "metoclopramide",
    name: "Metoclopramide",
    aliases: ["Reglan"],
    class: "Prokinetic / antiemetic",
    category: "GI",
    description: "D₂ antagonist and 5-HT₄ agonist-like prokinetic.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 5,
    freeConcNm: 100,
    bindings: [
      b("d2", 160, "Ki", "antagonist", 0.85),
      b("5ht3", 350, "Ki", "antagonist", 0.45),
    ],
  },
  {
    id: "loperamide",
    name: "Loperamide",
    aliases: ["Imodium"],
    class: "Peripheral opioid",
    category: "GI",
    description: "Peripheral μ-opioid agonist for diarrhea (low CNS entry).",
    defaultDoseMg: 2,
    doseUnit: "mg",
    halfLifeHours: 11,
    freeConcNm: 5,
    bindings: [b("mu-opioid", 3.3, "Ki", "agonist", 0.85, "Peripheral; P-gp limits CNS")],
  },

  // ——— Pain / neuro ———
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    aliases: ["Advil", "Motrin"],
    class: "NSAID",
    category: "Pain",
    description: "Non-selective COX-1/COX-2 inhibitor.",
    defaultDoseMg: 400,
    doseUnit: "mg",
    halfLifeHours: 2,
    freeConcNm: 20000,
    bindings: [
      b("cox1", 5000, "IC50", "inhibitor", 0.8),
      b("cox2", 1400, "IC50", "inhibitor", 0.85),
    ],
  },
  {
    id: "naproxen",
    name: "Naproxen",
    aliases: ["Aleve", "Naprosyn"],
    class: "NSAID",
    category: "Pain",
    description: "Longer-acting non-selective NSAID.",
    defaultDoseMg: 500,
    doseUnit: "mg",
    halfLifeHours: 14,
    freeConcNm: 15000,
    bindings: [
      b("cox1", 3200, "IC50", "inhibitor", 0.85),
      b("cox2", 2800, "IC50", "inhibitor", 0.85),
    ],
  },
  {
    id: "aspirin",
    name: "Aspirin",
    aliases: ["ASA", "acetylsalicylic acid"],
    class: "NSAID / antiplatelet",
    category: "Cardiovascular",
    description: "Irreversible COX-1 inhibitor; antiplatelet at low dose.",
    defaultDoseMg: 81,
    doseUnit: "mg",
    halfLifeHours: 0.3,
    freeConcNm: 5000,
    bindings: [
      b("cox1", 300, "IC50", "inhibitor", 0.98, "Irreversible acetylation"),
      b("cox2", 1200, "IC50", "inhibitor", 0.7),
    ],
  },
  {
    id: "acetaminophen",
    name: "Acetaminophen",
    aliases: ["Tylenol", "paracetamol"],
    class: "Analgesic / antipyretic",
    category: "Pain",
    description: "Central COX-related analgesia; weak peripheral COX.",
    defaultDoseMg: 500,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 30000,
    bindings: [
      b("cox2", 25000, "IC50", "inhibitor", 0.3, "Weak; central mechanisms dominate"),
      b("cox1", 50000, "IC50", "inhibitor", 0.2),
    ],
  },
  {
    id: "sumatriptan",
    name: "Sumatriptan",
    aliases: ["Imitrex"],
    class: "Triptan",
    category: "Pain",
    description: "5-HT₁B/₁D agonist for migraine.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 2,
    freeConcNm: 40,
    bindings: [
      b("5ht1b", 9.3, "Ki", "agonist", 0.95),
      b("5ht1d", 7.3, "Ki", "agonist", 0.95),
    ],
  },
  {
    id: "rizatriptan",
    name: "Rizatriptan",
    aliases: ["Maxalt"],
    class: "Triptan",
    category: "Pain",
    description: "Oral 5-HT₁B/₁D agonist for acute migraine.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 30,
    bindings: [
      b("5ht1b", 5.3, "Ki", "agonist", 0.95),
      b("5ht1d", 3.1, "Ki", "agonist", 0.95),
    ],
  },
  {
    id: "gabapentin",
    name: "Gabapentin",
    aliases: ["Neurontin"],
    class: "Gabapentinoid",
    category: "Neurology",
    description: "Binds α2δ subunit of voltage-gated Ca channels.",
    defaultDoseMg: 300,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 20000,
    bindings: [b("alpha2delta", 140, "Ki", "modulator-negative", 0.8)],
  },
  {
    id: "pregabalin",
    name: "Pregabalin",
    aliases: ["Lyrica"],
    class: "Gabapentinoid",
    category: "Neurology",
    description: "High-affinity α2δ ligand for neuropathic pain and anxiety.",
    defaultDoseMg: 75,
    doseUnit: "mg",
    halfLifeHours: 6.5,
    freeConcNm: 8000,
    bindings: [b("alpha2delta", 19, "Ki", "modulator-negative", 0.9)],
  },
  {
    id: "lamotrigine",
    name: "Lamotrigine",
    aliases: ["Lamictal"],
    class: "Anticonvulsant / mood stabilizer",
    category: "Neurology",
    description: "Voltage-gated Na⁺ channel modulator used for epilepsy and bipolar.",
    defaultDoseMg: 100,
    doseUnit: "mg",
    halfLifeHours: 25,
    freeConcNm: 15000,
    bindings: [
      b("nmda", 100000, "IC50", "antagonist", 0.15, "Indirect; primary action on Na channels"),
    ],
  },
  {
    id: "topiramate",
    name: "Topiramate",
    aliases: ["Topamax"],
    class: "Anticonvulsant",
    category: "Neurology",
    description: "Multi-target anticonvulsant (Na channels, GABA, AMPA/kainate).",
    defaultDoseMg: 100,
    doseUnit: "mg",
    halfLifeHours: 21,
    freeConcNm: 5000,
    bindings: [
      b("gaba-a", 2000, "EC50", "modulator-positive", 0.4),
      b("ampa", 1000, "IC50", "antagonist", 0.5),
    ],
  },
  {
    id: "ketamine",
    name: "Ketamine",
    aliases: ["Ketalar", "esketamine", "Spravato"],
    class: "NMDA antagonist",
    category: "Anesthetic",
    description: "Non-competitive NMDA antagonist; dissociative anesthetic / antidepressant.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 500,
    bindings: [
      b("nmda", 400, "Ki", "antagonist", 0.95, "PCP site Ki-range"),
      b("mu-opioid", 26000, "Ki", "agonist", 0.2),
      b("dat", 66000, "Ki", "inhibitor", 0.25),
    ],
  },
  {
    id: "memantine",
    name: "Memantine",
    aliases: ["Namenda"],
    class: "NMDA antagonist",
    category: "Neurology",
    description: "Uncompetitive NMDA antagonist for Alzheimer disease.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 70,
    freeConcNm: 200,
    bindings: [b("nmda", 500, "Ki", "antagonist", 0.65)],
  },
  {
    id: "donepezil",
    name: "Donepezil",
    aliases: ["Aricept"],
    class: "AChE inhibitor",
    category: "Neurology",
    description: "Acetylcholinesterase inhibitor for Alzheimer disease.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 70,
    freeConcNm: 20,
    bindings: [b("ache", 6.7, "IC50", "inhibitor", 0.95)],
  },
  {
    id: "baclofen",
    name: "Baclofen",
    aliases: ["Lioresal"],
    class: "GABA-B agonist",
    category: "Neurology",
    description: "GABA-B agonist muscle relaxant.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 500,
    bindings: [b("gaba-b", 200, "Ki", "agonist", 0.95)],
  },

  // ——— Cardiovascular / resp ———
  {
    id: "propranolol",
    name: "Propranolol",
    aliases: ["Inderal"],
    class: "Non-selective β-blocker",
    category: "Cardiovascular",
    description: "β₁/β₂ antagonist for HTN, tremor, migraine prophylaxis.",
    defaultDoseMg: 40,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 50,
    bindings: [
      b("beta1", 1.8, "Ki", "antagonist", 0.95),
      b("beta2", 0.8, "Ki", "antagonist", 0.95),
    ],
  },
  {
    id: "metoprolol",
    name: "Metoprolol",
    aliases: ["Lopressor", "Toprol"],
    class: "Selective β₁-blocker",
    category: "Cardiovascular",
    description: "Cardioselective β₁ antagonist.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 100,
    bindings: [
      b("beta1", 47, "Ki", "antagonist", 0.95),
      b("beta2", 3000, "Ki", "antagonist", 0.3),
    ],
  },
  {
    id: "carvedilol",
    name: "Carvedilol",
    aliases: ["Coreg"],
    class: "α/β-blocker",
    category: "Cardiovascular",
    description: "Non-selective β plus α₁ antagonist.",
    defaultDoseMg: 12.5,
    doseUnit: "mg",
    halfLifeHours: 7,
    freeConcNm: 20,
    bindings: [
      b("beta1", 0.8, "Ki", "antagonist", 0.9),
      b("beta2", 1.0, "Ki", "antagonist", 0.9),
      b("alpha1", 3.4, "Ki", "antagonist", 0.8),
    ],
  },
  {
    id: "prazosin",
    name: "Prazosin",
    aliases: ["Minipress"],
    class: "α₁ antagonist",
    category: "Cardiovascular",
    description: "α₁ antagonist for HTN and off-label PTSD nightmares.",
    defaultDoseMg: 2,
    doseUnit: "mg",
    halfLifeHours: 3,
    freeConcNm: 5,
    bindings: [b("alpha1", 0.1, "Ki", "antagonist", 0.95)],
  },
  {
    id: "albuterol",
    name: "Albuterol",
    aliases: ["salbutamol", "Ventolin", "ProAir"],
    class: "β₂ agonist",
    category: "Respiratory",
    description: "Short-acting β₂ agonist bronchodilator.",
    defaultDoseMg: 2.5,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 15,
    bindings: [
      b("beta2", 1.5, "Ki", "agonist", 0.95),
      b("beta1", 2000, "Ki", "agonist", 0.2),
    ],
  },
  {
    id: "clonidine",
    name: "Clonidine",
    aliases: ["Catapres"],
    class: "α₂ agonist",
    category: "Cardiovascular",
    description: "Central α₂ agonist for HTN and ADHD adjunct.",
    defaultDoseMg: 0.1,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 5,
    bindings: [b("alpha2", 1.3, "Ki", "agonist", 0.9)],
  },
  {
    id: "tamsulosin",
    name: "Tamsulosin",
    aliases: ["Flomax"],
    class: "α₁ antagonist",
    category: "Urology",
    description: "α₁A-preferring antagonist for BPH.",
    defaultDoseMg: 0.4,
    doseUnit: "mg",
    halfLifeHours: 14,
    freeConcNm: 2,
    bindings: [b("alpha1", 0.04, "Ki", "antagonist", 0.95, "α1A-preferring")],
  },
  {
    id: "pseudoephedrine",
    name: "Pseudoephedrine",
    aliases: ["Sudafed"],
    class: "Sympathomimetic",
    category: "Allergy",
    description: "Indirect α/β agonist decongestant.",
    defaultDoseMg: 60,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 500,
    bindings: [
      b("alpha1", 2000, "EC50", "agonist", 0.7, "Indirect; NET substrate effects dominate"),
      b("beta1", 5000, "EC50", "agonist", 0.4),
      b("beta2", 8000, "EC50", "agonist", 0.35),
      b("net", 300, "Ki", "releaser", 0.45),
    ],
  },
  {
    id: "phenylephrine",
    name: "Phenylephrine",
    aliases: ["Sudafed PE"],
    class: "α₁ agonist",
    category: "Allergy",
    description: "Selective α₁ agonist decongestant / vasopressor.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 2.5,
    freeConcNm: 100,
    bindings: [b("alpha1", 300, "Ki", "agonist", 0.9)],
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    aliases: ["Norvasc"],
    class: "Dihydropyridine CCB",
    category: "Cardiovascular",
    description: "L-type calcium channel blocker for HTN/angina.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 40,
    freeConcNm: 5,
    bindings: [b("lt-type-ca", 1.9, "IC50", "inhibitor", 0.95)],
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    aliases: ["Prinivil", "Zestril"],
    class: "ACE inhibitor",
    category: "Cardiovascular",
    description: "ACE inhibitor for HTN and heart failure.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 20,
    bindings: [b("ace", 0.4, "IC50", "inhibitor", 0.95)],
  },
  {
    id: "losartan",
    name: "Losartan",
    aliases: ["Cozaar"],
    class: "ARB",
    category: "Cardiovascular",
    description: "AT₁ receptor antagonist.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 80,
    bindings: [b("at1", 5, "Ki", "antagonist", 0.95)],
  },
  {
    id: "spironolactone",
    name: "Spironolactone",
    aliases: ["Aldactone"],
    class: "MRA",
    category: "Cardiovascular",
    description: "Mineralocorticoid receptor antagonist.",
    defaultDoseMg: 25,
    doseUnit: "mg",
    halfLifeHours: 1.5,
    freeConcNm: 50,
    bindings: [b("mr", 24, "Ki", "antagonist", 0.9)],
  },
  {
    id: "clopidogrel",
    name: "Clopidogrel",
    aliases: ["Plavix"],
    class: "P2Y₁₂ inhibitor",
    category: "Cardiovascular",
    description: "Irreversible P2Y₁₂ antagonist antiplatelet.",
    defaultDoseMg: 75,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 10,
    bindings: [b("p2y12", 2, "IC50", "antagonist", 0.95, "Active thiol metabolite")],
  },
  {
    id: "warfarin",
    name: "Warfarin",
    aliases: ["Coumadin"],
    class: "Vitamin K antagonist",
    category: "Cardiovascular",
    description: "VKORC1 inhibitor anticoagulant.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 40,
    freeConcNm: 2000,
    bindings: [b("vkorc1", 1.5, "Ki", "inhibitor", 0.98)],
  },
  {
    id: "apixaban",
    name: "Apixaban",
    aliases: ["Eliquis"],
    class: "Factor Xa inhibitor",
    category: "Cardiovascular",
    description: "Direct oral FXa inhibitor.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 12,
    freeConcNm: 50,
    bindings: [b("fXa", 0.08, "Ki", "inhibitor", 0.98)],
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    aliases: ["Lipitor"],
    class: "Statin",
    category: "Cardiovascular",
    description: "HMG-CoA reductase inhibitor.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 14,
    freeConcNm: 5,
    bindings: [b("hmgcr", 8, "IC50", "inhibitor", 0.95)],
  },
  {
    id: "rosuvastatin",
    name: "Rosuvastatin",
    aliases: ["Crestor"],
    class: "Statin",
    category: "Cardiovascular",
    description: "High-intensity HMG-CoA reductase inhibitor.",
    defaultDoseMg: 20,
    doseUnit: "mg",
    halfLifeHours: 19,
    freeConcNm: 3,
    bindings: [b("hmgcr", 5, "IC50", "inhibitor", 0.98)],
  },
  {
    id: "sildenafil",
    name: "Sildenafil",
    aliases: ["Viagra", "Revatio"],
    class: "PDE5 inhibitor",
    category: "Urology",
    description: "PDE5 inhibitor for ED and PAH.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 30,
    bindings: [b("pde5", 3.5, "IC50", "inhibitor", 0.95)],
  },
  {
    id: "metformin",
    name: "Metformin",
    aliases: ["Glucophage"],
    class: "Biguanide",
    category: "Endocrine",
    description: "First-line diabetes agent (AMPK pathway; limited receptor map).",
    defaultDoseMg: 500,
    doseUnit: "mg",
    halfLifeHours: 6,
    freeConcNm: 10000,
    bindings: [
      b("insulin-r", 50000, "EC50", "modulator-positive", 0.25, "Indirect insulin sensitivity"),
    ],
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    aliases: ["Ozempic", "Wegovy"],
    class: "GLP-1 RA",
    category: "Endocrine",
    description: "Long-acting GLP-1 receptor agonist.",
    defaultDoseMg: 0.5,
    doseUnit: "mg",
    halfLifeHours: 168,
    freeConcNm: 2,
    bindings: [b("glp1r", 0.15, "EC50", "agonist", 0.98)],
  },
  {
    id: "insulin",
    name: "Insulin (regular)",
    aliases: ["Humulin R", "Novolin R"],
    class: "Hormone",
    category: "Endocrine",
    description: "Insulin receptor agonist for glucose control.",
    defaultDoseMg: 5,
    doseUnit: "U",
    halfLifeHours: 0.5,
    freeConcNm: 0.5,
    bindings: [b("insulin-r", 0.2, "Kd", "agonist", 1.0, "High-affinity IR site")],
  },
  {
    id: "levothyroxine",
    name: "Levothyroxine",
    aliases: ["Synthroid", "T4"],
    class: "Thyroid hormone",
    category: "Endocrine",
    description: "Thyroid hormone receptor agonist (via T3 conversion).",
    defaultDoseMg: 0.1,
    doseUnit: "mg",
    halfLifeHours: 168,
    freeConcNm: 20,
    bindings: [b("thr", 0.5, "Kd", "agonist", 0.9, "T3 at THR; T4 is prohormone")],
  },
  {
    id: "prednisone",
    name: "Prednisone",
    aliases: ["Deltasone"],
    class: "Corticosteroid",
    category: "Immune",
    description: "Glucocorticoid receptor agonist.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 3,
    freeConcNm: 100,
    bindings: [
      b("gr", 5, "Kd", "agonist", 0.95, "Prednisolone active form"),
      b("mr", 100, "Kd", "agonist", 0.25),
    ],
  },
  {
    id: "fluticasone",
    name: "Fluticasone",
    aliases: ["Flonase", "Flovent"],
    class: "Inhaled corticosteroid",
    category: "Respiratory",
    description: "Topical GR agonist for asthma/rhinitis.",
    defaultDoseMg: 0.2,
    doseUnit: "mg",
    halfLifeHours: 8,
    freeConcNm: 1,
    bindings: [b("gr", 0.5, "Kd", "agonist", 0.95)],
  },
  {
    id: "montelukast",
    name: "Montelukast",
    aliases: ["Singulair"],
    class: "LTRA",
    category: "Respiratory",
    description: "CysLT₁ receptor antagonist.",
    defaultDoseMg: 10,
    doseUnit: "mg",
    halfLifeHours: 5,
    freeConcNm: 10,
    bindings: [b("cyslt1", 0.5, "Ki", "antagonist", 0.95)],
  },
  {
    id: "tiotropium",
    name: "Tiotropium",
    aliases: ["Spiriva"],
    class: "LAMA",
    category: "Respiratory",
    description: "Long-acting muscarinic antagonist for COPD.",
    defaultDoseMg: 0.018,
    doseUnit: "mg",
    halfLifeHours: 120,
    freeConcNm: 0.5,
    bindings: [
      b("m3", 0.01, "Kd", "antagonist", 0.95),
      b("m1", 0.05, "Kd", "antagonist", 0.8),
      b("m2", 0.1, "Kd", "antagonist", 0.65),
    ],
  },
  {
    id: "melatonin",
    name: "Melatonin",
    aliases: ["N-acetyl-5-methoxytryptamine"],
    class: "Hormone supplement",
    category: "Sleep",
    description: "MT₁/MT₂ agonist for sleep onset.",
    defaultDoseMg: 3,
    doseUnit: "mg",
    halfLifeHours: 0.75,
    freeConcNm: 5,
    bindings: [
      b("mt1", 0.08, "Ki", "agonist", 0.9),
      b("mt2", 0.3, "Ki", "agonist", 0.9),
    ],
  },
  {
    id: "thc",
    name: "THC (dronabinol)",
    aliases: ["Marinol", "delta-9-THC"],
    class: "Cannabinoid",
    category: "Other",
    description: "CB₁/CB₂ partial agonist.",
    defaultDoseMg: 5,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 20,
    bindings: [
      b("cb1", 10, "Ki", "partial-agonist", 0.7),
      b("cb2", 24, "Ki", "partial-agonist", 0.5),
    ],
  },
  {
    id: "cbd",
    name: "CBD (cannabidiol)",
    aliases: ["Epidiolex"],
    class: "Cannabinoid",
    category: "Other",
    description: "Low CB₁ affinity; multi-target neuromodulator.",
    defaultDoseMg: 50,
    doseUnit: "mg",
    halfLifeHours: 18,
    freeConcNm: 200,
    bindings: [
      b("cb1", 4350, "Ki", "antagonist", 0.25),
      b("cb2", 2800, "Ki", "partial-agonist", 0.3),
      b("5ht1a", 16000, "Ki", "agonist", 0.35),
    ],
  },
  {
    id: "dextromethorphan",
    name: "Dextromethorphan",
    aliases: ["DXM", "Robitussin"],
    class: "Antitussive",
    category: "Other",
    description: "σ₁ agonist and NMDA antagonist cough suppressant.",
    defaultDoseMg: 30,
    doseUnit: "mg",
    halfLifeHours: 4,
    freeConcNm: 200,
    bindings: [
      b("sigma1", 150, "Ki", "agonist", 0.8),
      b("nmda", 1400, "Ki", "antagonist", 0.5),
      b("sert", 23, "Ki", "inhibitor", 0.3, "S-enantiomer contribution varies"),
    ],
  },
];

export const DRUGS: Drug[] = RAW_DRUGS.map((d) => ({
  ...d,
  bindings: d.bindings.map(normalizeBinding),
}));

export const DRUG_MAP = Object.fromEntries(DRUGS.map((d) => [d.id, d])) as Record<
  string,
  Drug
>;

export const DRUG_CATEGORIES = [
  ...new Set(DRUGS.map((d) => d.category)),
].sort();

export function searchDrugs(query: string): Drug[] {
  const q = query.trim().toLowerCase();
  if (!q) return DRUGS;
  return DRUGS.filter((d) => {
    if (d.name.toLowerCase().includes(q)) return true;
    if (d.class.toLowerCase().includes(q)) return true;
    if (d.category.toLowerCase().includes(q)) return true;
    if (d.aliases.some((a) => a.toLowerCase().includes(q))) return true;
    if (d.bindings.some((b) => b.receptorId.includes(q))) return true;
    if (d.bindings.some((b) => b.metric.toLowerCase().includes(q))) return true;
    return false;
  });
}

export interface PresetItem {
  drugId: string;
  /** Optional dose override (mg/U). Defaults to drug.defaultDoseMg. */
  doseMg?: number;
}

export interface PresetCocktail {
  id: string;
  name: string;
  /** Specific named drugs, e.g. "Sertraline 50 mg + Bupropion 150 mg". */
  drugsLabel: string;
  description: string;
  /** What the user should notice after loading. */
  highlight: string;
  tag: "risk" | "reversal" | "common" | "compare" | "cardiovascular" | "cns";
  items: PresetItem[];
  /** Convenience list of ids (derived from items). */
  drugIds: string[];
}

function preset(
  p: Omit<PresetCocktail, "drugIds"> & { items: PresetItem[] },
): PresetCocktail {
  return { ...p, drugIds: p.items.map((i) => i.drugId) };
}

/** Named real-world style example regimens with specific drugs and doses. */
export const PRESETS: PresetCocktail[] = [
  preset({
    id: "morphine-narcan",
    name: "Morphine vs Narcan",
    drugsLabel: "Morphine 15 mg + Naloxone 2 mg",
    description:
      "Classic overdose-reversal pair. Watch μ-opioid occupancy flip from agonist-dominant to antagonist-dominant.",
    highlight: "Naloxone Ki 1.1 nM outcompetes morphine Ki 1.8 nM at MOR.",
    tag: "reversal",
    items: [
      { drugId: "morphine", doseMg: 15 },
      { drugId: "naloxone", doseMg: 2 },
    ],
  }),
  preset({
    id: "suboxone-like",
    name: "Buprenorphine partial agonism",
    drugsLabel: "Buprenorphine 8 mg + Naloxone 2 mg",
    description:
      "Suboxone-style stack. High-affinity μ partial agonist with low ceiling; naloxone is oral-inactive but visible in the map.",
    highlight: "Buprenorphine MOR Ki ~0.22 nM with only partial efficacy.",
    tag: "compare",
    items: [
      { drugId: "buprenorphine", doseMg: 8 },
      { drugId: "naloxone", doseMg: 2 },
    ],
  }),
  preset({
    id: "methadone-naltrexone",
    name: "Methadone blocked by naltrexone",
    drugsLabel: "Methadone 20 mg + Naltrexone 50 mg",
    description:
      "Long-acting agonist confronted by long-acting antagonist at μ receptors.",
    highlight: "Naltrexone Ki 0.34 nM collapses methadone μ activity.",
    tag: "reversal",
    items: [
      { drugId: "methadone", doseMg: 20 },
      { drugId: "naltrexone", doseMg: 50 },
    ],
  }),
  preset({
    id: "percocet-xanax-lyrica",
    name: "OxyContin + Xanax + Lyrica",
    drugsLabel: "Oxycodone 10 mg + Alprazolam 0.5 mg + Pregabalin 75 mg",
    description:
      "High-risk CNS depression triad seen in polypharmacy pain/anxiety cases.",
    highlight: "μ agonism + GABA-A PAM + α2δ modulation stack sedation risk.",
    tag: "risk",
    items: [
      { drugId: "oxycodone", doseMg: 10 },
      { drugId: "alprazolam", doseMg: 0.5 },
      { drugId: "pregabalin", doseMg: 75 },
    ],
  }),
  preset({
    id: "vicodin-ambien",
    name: "Vicodin + Ambien",
    drugsLabel: "Hydrocodone 10 mg + Zolpidem 5 mg",
    description: "Opioid + Z-drug co-use; shared CNS depression without a formal benzo.",
    highlight: "μ occupancy + α1-preferring GABA-A modulation.",
    tag: "risk",
    items: [
      { drugId: "hydrocodone", doseMg: 10 },
      { drugId: "zolpidem", doseMg: 5 },
    ],
  }),
  preset({
    id: "zoloft-wellbutrin-desyrel",
    name: "Zoloft + Wellbutrin + Desyrel",
    drugsLabel: "Sertraline 50 mg + Bupropion 150 mg + Trazodone 50 mg",
    description:
      "Common depression polypharmacy: SSRI by day, NDRI boost, trazodone for sleep.",
    highlight: "SERT, DAT/NET, and 5-HT₂A/H₁ all light up together.",
    tag: "common",
    items: [
      { drugId: "sertraline", doseMg: 50 },
      { drugId: "bupropion", doseMg: 150 },
      { drugId: "trazodone", doseMg: 50 },
    ],
  }),
  preset({
    id: "prozac-ultram",
    name: "Prozac + Ultram risk",
    drugsLabel: "Fluoxetine 20 mg + Tramadol 50 mg",
    description:
      "SSRI + serotonergic opioid — textbook serotonin-toxicity teaching case.",
    highlight: "SERT inhibition stacks; check risk synergies panel.",
    tag: "risk",
    items: [
      { drugId: "fluoxetine", doseMg: 20 },
      { drugId: "tramadol", doseMg: 50 },
    ],
  }),
  preset({
    id: "lexapro-cymbalta",
    name: "Lexapro + Cymbalta",
    drugsLabel: "Escitalopram 10 mg + Duloxetine 60 mg",
    description: "SSRI + SNRI dual monoamine reuptake — additive SERT/NET tone.",
    highlight: "SERT competition with SNRI NET contribution.",
    tag: "common",
    items: [
      { drugId: "escitalopram", doseMg: 10 },
      { drugId: "duloxetine", doseMg: 60 },
    ],
  }),
  preset({
    id: "adderall-strattera",
    name: "Adderall vs Strattera",
    drugsLabel: "Amphetamine 10 mg + Atomoxetine 40 mg",
    description:
      "Stimulant releaser beside selective NET inhibitor — compare DAT vs NET maps.",
    highlight: "DAT/VMAT2 release vs pure NET Ki 5 nM inhibition.",
    tag: "compare",
    items: [
      { drugId: "amphetamine", doseMg: 10 },
      { drugId: "atomoxetine", doseMg: 40 },
    ],
  }),
  preset({
    id: "vyvanse-ritalin",
    name: "Vyvanse + Ritalin",
    drugsLabel: "Lisdexamfetamine 30 mg + Methylphenidate 20 mg",
    description: "Two ADHD mechanisms at DAT: releaser prodrug + reuptake inhibitor.",
    highlight: "Both weight DAT; competitive occupancy shifts with dose.",
    tag: "compare",
    items: [
      { drugId: "lisdexamfetamine", doseMg: 30 },
      { drugId: "methylphenidate", doseMg: 20 },
    ],
  }),
  preset({
    id: "abilify-lexapro",
    name: "Abilify + Lexapro",
    drugsLabel: "Aripiprazole 10 mg + Escitalopram 10 mg",
    description:
      "Adjunct antipsychotic + SSRI. Partial D₂ agonism vs pure SERT inhibition.",
    highlight: "D₂ partial agonist (Ki 0.34 nM) + SERT Ki ~1 nM.",
    tag: "common",
    items: [
      { drugId: "aripiprazole", doseMg: 10 },
      { drugId: "escitalopram", doseMg: 10 },
    ],
  }),
  preset({
    id: "zyprexa-ativan",
    name: "Zyprexa + Ativan",
    drugsLabel: "Olanzapine 10 mg + Lorazepam 1 mg",
    description:
      "Sedating antipsychotic + benzo — heavy H₁/M₁ antagonism plus GABA-A PAM.",
    highlight: "Olanzapine H₁ Ki ~0.1 nM drives sedation; lorazepam adds BZ tone.",
    tag: "risk",
    items: [
      { drugId: "olanzapine", doseMg: 10 },
      { drugId: "lorazepam", doseMg: 1 },
    ],
  }),
  preset({
    id: "haldol-ativan",
    name: "Haldol + Ativan",
    drugsLabel: "Haloperidol 5 mg + Lorazepam 1 mg",
    description: "Classic acute agitation cocktail — D₂ blockade + benzo.",
    highlight: "Haloperidol D₂ Ki 0.7 nM; lorazepam BZ Ki ~2 nM.",
    tag: "cns",
    items: [
      { drugId: "haloperidol", doseMg: 5 },
      { drugId: "lorazepam", doseMg: 1 },
    ],
  }),
  preset({
    id: "lipitor-norvasc-zestril",
    name: "Lipitor + Norvasc + Zestril",
    drugsLabel: "Atorvastatin 20 mg + Amlodipine 5 mg + Lisinopril 10 mg",
    description: "Everyday primary-care CV stack: lipid + CCB + ACEI.",
    highlight: "HMGCR, L-type Ca²⁺, and ACE in parallel — complementary, not competitive.",
    tag: "cardiovascular",
    items: [
      { drugId: "atorvastatin", doseMg: 20 },
      { drugId: "amlodipine", doseMg: 5 },
      { drugId: "lisinopril", doseMg: 10 },
    ],
  }),
  preset({
    id: "coreg-lasix-like",
    name: "Coreg + Aldactone + Eliquis",
    drugsLabel: "Carvedilol 12.5 mg + Spironolactone 25 mg + Apixaban 5 mg",
    description: "HF / AF style combo: α/β-blockade, MRA, and FXa inhibition.",
    highlight: "β₁/β₂/α₁ + MR + FXa Ki 0.08 nM.",
    tag: "cardiovascular",
    items: [
      { drugId: "carvedilol", doseMg: 12.5 },
      { drugId: "spironolactone", doseMg: 25 },
      { drugId: "apixaban", doseMg: 5 },
    ],
  }),
  preset({
    id: "dual-antiplatelet",
    name: "Aspirin + Plavix DAPT",
    drugsLabel: "Aspirin 81 mg + Clopidogrel 75 mg",
    description: "Dual antiplatelet therapy after coronary stenting.",
    highlight: "COX-1 irreversible block + P2Y₁₂ antagonism synergy.",
    tag: "cardiovascular",
    items: [
      { drugId: "aspirin", doseMg: 81 },
      { drugId: "clopidogrel", doseMg: 75 },
    ],
  }),
  preset({
    id: "propranolol-albuterol",
    name: "Inderal vs Ventolin",
    drugsLabel: "Propranolol 40 mg + Albuterol 2.5 mg",
    description:
      "Non-selective β-blockade opposing β₂ bronchodilation — teaching case for asthma.",
    highlight: "Propranolol β₂ Ki 0.8 nM blunts albuterol β₂ agonism.",
    tag: "risk",
    items: [
      { drugId: "propranolol", doseMg: 40 },
      { drugId: "albuterol", doseMg: 2.5 },
    ],
  }),
  preset({
    id: "imitrex-zoloft",
    name: "Imitrex + Zoloft",
    drugsLabel: "Sumatriptan 50 mg + Sertraline 50 mg",
    description: "Triptan on an SSRI — serotonergic load teaching example.",
    highlight: "5-HT₁B/₁D agonism with SERT Ki 0.29 nM inhibition.",
    tag: "risk",
    items: [
      { drugId: "sumatriptan", doseMg: 50 },
      { drugId: "sertraline", doseMg: 50 },
    ],
  }),
  preset({
    id: "maxalt-motrin-zofran",
    name: "Maxalt + Motrin + Zofran",
    drugsLabel: "Rizatriptan 10 mg + Ibuprofen 400 mg + Ondansetron 8 mg",
    description: "Acute migraine kit: triptan, NSAID, and antiemetic.",
    highlight: "5-HT₁B/₁D + COX + 5-HT₃ each own distinct receptors.",
    tag: "common",
    items: [
      { drugId: "rizatriptan", doseMg: 10 },
      { drugId: "ibuprofen", doseMg: 400 },
      { drugId: "ondansetron", doseMg: 8 },
    ],
  }),
  preset({
    id: "chantix-nicotine",
    name: "Chantix vs nicotine",
    drugsLabel: "Varenicline 1 mg + Nicotine 4 mg",
    description:
      "Partial α4β2 agonist competing with full nicotine agonism at nAChR.",
    highlight: "Varenicline Ki ~0.15 nM partial vs nicotine Ki ~1 nM full agonist.",
    tag: "compare",
    items: [
      { drugId: "varenicline", doseMg: 1 },
      { drugId: "nicotine", doseMg: 4 },
    ],
  }),
  preset({
    id: "ambien-benadryl-melatonin",
    name: "Ambien + Benadryl + melatonin",
    drugsLabel: "Zolpidem 5 mg + Diphenhydramine 25 mg + Melatonin 3 mg",
    description: "Stacked sleep aids across BZ site, H₁, and MT₁/MT₂.",
    highlight: "Three independent sleep pathways; additive sedation risk.",
    tag: "risk",
    items: [
      { drugId: "zolpidem", doseMg: 5 },
      { drugId: "diphenhydramine", doseMg: 25 },
      { drugId: "melatonin", doseMg: 3 },
    ],
  }),
  preset({
    id: "ozempic-metformin",
    name: "Ozempic + Glucophage",
    drugsLabel: "Semaglutide 0.5 mg + Metformin 500 mg",
    description: "Modern T2DM / weight-loss backbone: GLP-1 RA + biguanide.",
    highlight: "GLP-1R EC₅₀ ~0.15 nM with metformin’s indirect insulin-path tone.",
    tag: "common",
    items: [
      { drugId: "semaglutide", doseMg: 0.5 },
      { drugId: "metformin", doseMg: 500 },
    ],
  }),
  preset({
    id: "aricept-benadryl",
    name: "Aricept vs Benadryl",
    drugsLabel: "Donepezil 10 mg + Diphenhydramine 25 mg",
    description:
      "Cholinesterase inhibitor opposed by anticholinergic antihistamine — Beers-list teaching case.",
    highlight: "AChE IC₅₀ 6.7 nM vs M₁–M₃ antagonism cancels pro-cholinergic benefit.",
    tag: "risk",
    items: [
      { drugId: "donepezil", doseMg: 10 },
      { drugId: "diphenhydramine", doseMg: 25 },
    ],
  }),
  preset({
    id: "cold-otc",
    name: "OTC cold multi-symptom",
    drugsLabel: "Pseudoephedrine 60 mg + Diphenhydramine 25 mg + Acetaminophen 500 mg + DXM 30 mg",
    description: "Typical multi-symptom cold stack from the pharmacy aisle.",
    highlight: "α/β, H₁/mACh, weak COX, and σ₁/NMDA/SERT all appear.",
    tag: "common",
    items: [
      { drugId: "pseudoephedrine", doseMg: 60 },
      { drugId: "diphenhydramine", doseMg: 25 },
      { drugId: "acetaminophen", doseMg: 500 },
      { drugId: "dextromethorphan", doseMg: 30 },
    ],
  }),
  preset({
    id: "fentanyl-dilaudid",
    name: "Fentanyl vs Dilaudid potency",
    drugsLabel: "Fentanyl 0.1 mg + Hydromorphone 2 mg",
    description:
      "Compare two high-potency μ agonists by Ki and occupancy at the same dose scale.",
    highlight: "Fentanyl MOR Ki ~0.7 nM vs hydromorphone ~0.6 nM — both sub-nM class.",
    tag: "compare",
    items: [
      { drugId: "fentanyl", doseMg: 0.1 },
      { drugId: "hydromorphone", doseMg: 2 },
    ],
  }),
  preset({
    id: "thc-cbd",
    name: "THC + CBD cannabis",
    drugsLabel: "THC 5 mg + CBD 50 mg",
    description: "Cannabinoid pair: CB₁ partial agonism modulated by CBD.",
    highlight: "THC CB₁ Ki ~10 nM; CBD weak CB₁ antagonist attenuates tone.",
    tag: "compare",
    items: [
      { drugId: "thc", doseMg: 5 },
      { drugId: "cbd", doseMg: 50 },
    ],
  }),
  preset({
    id: "valium-alcohol",
    name: "Valium + alcohol",
    drugsLabel: "Diazepam 5 mg + Ethanol ~14 g",
    description: "Classic GABA-A / NMDA dual depressant interaction.",
    highlight: "BZ site PAM + ethanol GABA/NMDA effects — high risk synergy.",
    tag: "risk",
    items: [
      { drugId: "diazepam", doseMg: 5 },
      { drugId: "ethanol", doseMg: 14000 },
    ],
  }),
  preset({
    id: "spravato-ativan",
    name: "Ketamine + Ativan",
    drugsLabel: "Ketamine 50 mg + Lorazepam 1 mg",
    description:
      "NMDA antagonist with benzo on board — benzos can blunt dissociative intensity.",
    highlight: "NMDA Ki ~400 nM vs GABA-A PAM; check antagonistic synergy rule.",
    tag: "cns",
    items: [
      { drugId: "ketamine", doseMg: 50 },
      { drugId: "lorazepam", doseMg: 1 },
    ],
  }),
];

/** Resolve preset items to SelectedDrug-compatible objects. */
export function presetToSelection(
  p: PresetCocktail,
): { drugId: string; doseMg: number }[] {
  return p.items
    .map((item) => {
      const drug = DRUG_MAP[item.drugId];
      if (!drug) return null;
      return {
        drugId: item.drugId,
        doseMg: item.doseMg ?? drug.defaultDoseMg,
      };
    })
    .filter((x): x is { drugId: string; doseMg: number } => x !== null);
}
