import type { ReceptorDef } from "./types";

export const RECEPTORS: ReceptorDef[] = [
  { id: "mu-opioid", name: "μ-Opioid receptor (MOR)", shortName: "μ-Opioid", family: "Opioid", description: "Primary target for opioid analgesia and respiratory depression." },
  { id: "kappa-opioid", name: "κ-Opioid receptor (KOR)", shortName: "κ-Opioid", family: "Opioid", description: "Mediates dysphoria and some analgesia." },
  { id: "delta-opioid", name: "δ-Opioid receptor (DOR)", shortName: "δ-Opioid", family: "Opioid", description: "Modulates mood and analgesia." },
  { id: "d2", name: "Dopamine D₂ receptor", shortName: "D₂", family: "Dopaminergic", description: "Central to antipsychotics, antiemetics, and reward pathways." },
  { id: "d1", name: "Dopamine D₁ receptor", shortName: "D₁", family: "Dopaminergic", description: "Excitatory dopamine receptor in striatum and cortex." },
  { id: "dat", name: "Dopamine transporter (DAT)", shortName: "DAT", family: "Enzyme / Transporter", description: "Reuptake of synaptic dopamine." },
  { id: "sert", name: "Serotonin transporter (SERT)", shortName: "SERT", family: "Enzyme / Transporter", description: "Reuptake of synaptic 5-HT; primary SSRI target." },
  { id: "net", name: "Norepinephrine transporter (NET)", shortName: "NET", family: "Enzyme / Transporter", description: "Reuptake of synaptic norepinephrine." },
  { id: "5ht1a", name: "5-HT₁A receptor", shortName: "5-HT₁A", family: "Serotonergic", description: "Anxiolytic and antidepressant signaling." },
  { id: "5ht1b", name: "5-HT₁B receptor", shortName: "5-HT₁B", family: "Serotonergic", description: "Cranial vasoconstriction; triptan target." },
  { id: "5ht1d", name: "5-HT₁D receptor", shortName: "5-HT₁D", family: "Serotonergic", description: "Migraine-related serotonergic receptor." },
  { id: "5ht2a", name: "5-HT₂A receptor", shortName: "5-HT₂A", family: "Serotonergic", description: "Psychotomimetic and antipsychotic target." },
  { id: "5ht2c", name: "5-HT₂C receptor", shortName: "5-HT₂C", family: "Serotonergic", description: "Appetite and mood regulation." },
  { id: "5ht3", name: "5-HT₃ receptor", shortName: "5-HT₃", family: "Serotonergic", description: "Ionotropic receptor mediating nausea/vomiting." },
  { id: "alpha1", name: "α₁-Adrenergic receptor", shortName: "α₁", family: "Adrenergic", description: "Vascular smooth muscle contraction." },
  { id: "alpha2", name: "α₂-Adrenergic receptor", shortName: "α₂", family: "Adrenergic", description: "Presynaptic inhibition of NE release." },
  { id: "beta1", name: "β₁-Adrenergic receptor", shortName: "β₁", family: "Adrenergic", description: "Cardiac rate and contractility." },
  { id: "beta2", name: "β₂-Adrenergic receptor", shortName: "β₂", family: "Adrenergic", description: "Bronchodilation and vascular tone." },
  { id: "h1", name: "Histamine H₁ receptor", shortName: "H₁", family: "Histamine", description: "Allergy, wakefulness, and sedation." },
  { id: "h2", name: "Histamine H₂ receptor", shortName: "H₂", family: "Histamine", description: "Gastric acid secretion." },
  { id: "m1", name: "Muscarinic M₁ receptor", shortName: "M₁", family: "Cholinergic", description: "CNS cognition and autonomic signaling." },
  { id: "m2", name: "Muscarinic M₂ receptor", shortName: "M₂", family: "Cholinergic", description: "Cardiac slowing." },
  { id: "m3", name: "Muscarinic M₃ receptor", shortName: "M₃", family: "Cholinergic", description: "Smooth muscle and glandular secretion." },
  { id: "nachr", name: "Nicotinic ACh receptor (α4β2)", shortName: "nAChR", family: "Cholinergic", description: "CNS attention and reward; nicotine target." },
  { id: "gaba-a", name: "GABA-A receptor", shortName: "GABA-A", family: "GABA / Glutamate", description: "Inhibitory chloride channel; benzodiazepine site." },
  { id: "gaba-b", name: "GABA-B receptor", shortName: "GABA-B", family: "GABA / Glutamate", description: "Metabotropic inhibitory receptor." },
  { id: "nmda", name: "NMDA receptor", shortName: "NMDA", family: "GABA / Glutamate", description: "Excitatory glutamate receptor; memory and pain." },
  { id: "ampa", name: "AMPA receptor", shortName: "AMPA", family: "GABA / Glutamate", description: "Fast excitatory glutamate transmission." },
  { id: "cb1", name: "Cannabinoid CB₁ receptor", shortName: "CB₁", family: "Cannabinoid", description: "CNS psychoactive cannabinoid effects." },
  { id: "cb2", name: "Cannabinoid CB₂ receptor", shortName: "CB₂", family: "Cannabinoid", description: "Immune and peripheral cannabinoid signaling." },
  { id: "a1", name: "Adenosine A₁ receptor", shortName: "A₁", family: "Other", description: "Promotes sleep and cardiac slowing." },
  { id: "a2a", name: "Adenosine A₂A receptor", shortName: "A₂A", family: "Other", description: "Wakefulness and vascular tone; caffeine target." },
  { id: "mt1", name: "Melatonin MT₁ receptor", shortName: "MT₁", family: "Peptide / Hormone", description: "Sleep onset signaling." },
  { id: "mt2", name: "Melatonin MT₂ receptor", shortName: "MT₂", family: "Peptide / Hormone", description: "Circadian phase shifting." },
  { id: "glp1r", name: "GLP-1 receptor", shortName: "GLP-1R", family: "Peptide / Hormone", description: "Incretin pathway; appetite and glucose control." },
  { id: "insulin-r", name: "Insulin receptor", shortName: "IR", family: "Peptide / Hormone", description: "Glucose uptake and anabolism." },
  { id: "thr", name: "Thyroid hormone receptor", shortName: "THR", family: "Peptide / Hormone", description: "Metabolic rate and development." },
  { id: "gr", name: "Glucocorticoid receptor", shortName: "GR", family: "Peptide / Hormone", description: "Anti-inflammatory and stress axis." },
  { id: "at1", name: "Angiotensin II AT₁ receptor", shortName: "AT₁", family: "Peptide / Hormone", description: "Vasoconstriction and aldosterone release." },
  { id: "mr", name: "Mineralocorticoid receptor", shortName: "MR", family: "Peptide / Hormone", description: "Sodium retention and BP control." },
  { id: "p2y12", name: "P2Y₁₂ receptor", shortName: "P2Y₁₂", family: "Other", description: "Platelet aggregation." },
  { id: "lt-type-ca", name: "L-type Ca²⁺ channel", shortName: "L-Ca²⁺", family: "Ion channel", description: "Vascular and cardiac calcium entry." },
  { id: "alpha2delta", name: "Voltage-gated Ca²⁺ α2δ", shortName: "α2δ", family: "Ion channel", description: "Gabapentinoid binding site on Ca channels." },
  { id: "cox1", name: "COX-1 (PTGS1)", shortName: "COX-1", family: "Enzyme / Transporter", description: "Constitutive prostaglandin synthesis." },
  { id: "cox2", name: "COX-2 (PTGS2)", shortName: "COX-2", family: "Enzyme / Transporter", description: "Inducible inflammatory prostaglandins." },
  { id: "pde5", name: "PDE5", shortName: "PDE5", family: "Enzyme / Transporter", description: "cGMP breakdown; erectile physiology." },
  { id: "ache", name: "Acetylcholinesterase", shortName: "AChE", family: "Enzyme / Transporter", description: "Hydrolyzes acetylcholine at synapses." },
  { id: "hmgcr", name: "HMG-CoA reductase", shortName: "HMGCR", family: "Enzyme / Transporter", description: "Rate-limiting step of cholesterol synthesis." },
  { id: "ace", name: "Angiotensin-converting enzyme", shortName: "ACE", family: "Enzyme / Transporter", description: "Converts Ang I → Ang II." },
  { id: "vkorc1", name: "VKORC1", shortName: "VKORC1", family: "Enzyme / Transporter", description: "Vitamin K recycling; warfarin target." },
  { id: "fXa", name: "Factor Xa", shortName: "FXa", family: "Enzyme / Transporter", description: "Coagulation cascade protease." },
  { id: "gaba-a-bz", name: "GABA-A benzodiazepine site", shortName: "BZ site", family: "GABA / Glutamate", description: "Allosteric site potentiating GABA-A." },
  { id: "taar1", name: "TAAR1", shortName: "TAAR1", family: "Monoamine", description: "Trace amine receptor; stimulant intracellular signaling." },
  { id: "vmat2", name: "VMAT2", shortName: "VMAT2", family: "Enzyme / Transporter", description: "Vesicular monoamine packaging." },
  { id: "cyslt1", name: "CysLT₁ receptor", shortName: "CysLT₁", family: "Other", description: "Leukotriene-mediated bronchoconstriction." },
  { id: "sigma1", name: "σ₁ receptor", shortName: "σ₁", family: "Other", description: "Chaperone receptor; cough suppressant affinity." },

  { id: "d3", name: "Dopamine D₃ receptor", shortName: "D₃", family: "Dopaminergic", description: "Limbic dopamine receptor; antipsychotic and craving target." },
  { id: "d4", name: "Dopamine D₄ receptor", shortName: "D₄", family: "Dopaminergic", description: "Cortical dopamine receptor subtype." },
  { id: "5ht6", name: "5-HT₆ receptor", shortName: "5-HT₆", family: "Serotonergic", description: "Cognition-linked serotonergic receptor." },
  { id: "5ht7", name: "5-HT₇ receptor", shortName: "5-HT₇", family: "Serotonergic", description: "Circadian and mood-related 5-HT receptor." },
  { id: "5ht2b", name: "5-HT₂B receptor", shortName: "5-HT₂B", family: "Serotonergic", description: "Cardiac valvulopathy-linked serotonergic receptor." },
  { id: "mao-a", name: "Monoamine oxidase A", shortName: "MAO-A", family: "Enzyme / Transporter", description: "Oxidative deamination of 5-HT, NE, and DA." },
  { id: "mao-b", name: "Monoamine oxidase B", shortName: "MAO-B", family: "Enzyme / Transporter", description: "Preferential DA and phenylethylamine metabolism." },
  { id: "ox1", name: "Orexin OX₁ receptor", shortName: "OX₁", family: "Peptide / Hormone", description: "Wake-promoting orexin receptor." },
  { id: "ox2", name: "Orexin OX₂ receptor", shortName: "OX₂", family: "Peptide / Hormone", description: "Sleep–wake orexin receptor; dual antagonists promote sleep." },
  { id: "nk1", name: "Neurokinin-1 (NK₁) receptor", shortName: "NK₁", family: "Peptide / Hormone", description: "Substance P receptor; antiemetic target." },
  { id: "sv2a", name: "Synaptic vesicle protein 2A", shortName: "SV2A", family: "Other", description: "Presynaptic target of levetiracetam-class anticonvulsants." },
  { id: "h3", name: "Histamine H₃ receptor", shortName: "H₃", family: "Histamine", description: "Presynaptic histamine autoreceptor; wake/cognition." },
  { id: "n-type-ca", name: "N-type Ca²⁺ channel", shortName: "N-Ca²⁺", family: "Ion channel", description: "Presynaptic calcium channel involved in transmitter release." },
  { id: "nav", name: "Voltage-gated Na⁺ channel", shortName: "NaV", family: "Ion channel", description: "Action-potential sodium channels; anticonvulsant/local anesthetic target." },
  { id: "dpp4", name: "Dipeptidyl peptidase-4", shortName: "DPP-4", family: "Enzyme / Transporter", description: "Incretin-degrading protease; gliptin target." },
  { id: "sglt2", name: "SGLT2", shortName: "SGLT2", family: "Enzyme / Transporter", description: "Renal glucose reuptake transporter." },
  { id: "ppar-g", name: "PPAR-γ", shortName: "PPAR-γ", family: "Peptide / Hormone", description: "Nuclear receptor regulating insulin sensitivity." },
  { id: "comt", name: "Catechol-O-methyltransferase", shortName: "COMT", family: "Enzyme / Transporter", description: "Catecholamine methylation enzyme." },
  { id: "d2-partial", name: "Dopamine D₂ (partial-agonist sensitive)", shortName: "D₂*", family: "Dopaminergic", description: "Functional D₂ site emphasizing partial-agonist antipsychotics." },

];

export const RECEPTOR_MAP = Object.fromEntries(
  RECEPTORS.map((r) => [r.id, r]),
) as Record<string, ReceptorDef>;
