import type { SynergyRule } from "./types";

/** Curated interaction / synergy rules between drug pairs. */
export const SYNERGIES: SynergyRule[] = [
  {
    id: "ssri-tramadol-serotonin",
    drugIds: ["sertraline", "tramadol"],
    receptorIds: ["sert", "5ht1a", "5ht2a"],
    multiplier: 1.45,
    type: "risk",
    title: "Serotonergic potentiation",
    description:
      "SSRI + tramadol both raise serotonergic tone (SERT inhibition ± weak μ activity). Net 5-HT signaling rises; serotonin toxicity risk increases.",
    severity: "high",
  },
  {
    id: "ssri-maoi-like-duloxetine",
    drugIds: ["sertraline", "duloxetine"],
    receptorIds: ["sert", "net"],
    multiplier: 1.35,
    type: "synergistic",
    title: "Dual monoamine reuptake stack",
    description:
      "SSRI + SNRI combine at SERT (and NET for duloxetine). Binding competition at SERT with additive monoamine elevation.",
    severity: "moderate",
  },
  {
    id: "escitalopram-duloxetine",
    drugIds: ["escitalopram", "duloxetine"],
    receptorIds: ["sert", "net"],
    multiplier: 1.35,
    type: "synergistic",
    title: "Lexapro + Cymbalta monoamine stack",
    description:
      "Escitalopram SERT inhibition with duloxetine SERT/NET — dual reuptake tone.",
    severity: "moderate",
  },
  {
    id: "benzo-opioid-cns",
    drugIds: ["alprazolam", "oxycodone"],
    receptorIds: ["gaba-a", "gaba-a-bz", "mu-opioid"],
    multiplier: 1.55,
    type: "risk",
    title: "CNS / respiratory depression synergy",
    description:
      "Benzodiazepine GABA-A positive modulation plus μ-opioid agonism produce synergistic sedation and respiratory depression.",
    severity: "high",
  },
  {
    id: "alprazolam-pregabalin-oxy",
    drugIds: ["alprazolam", "pregabalin"],
    receptorIds: ["gaba-a", "gaba-a-bz", "alpha2delta"],
    multiplier: 1.4,
    type: "risk",
    title: "Xanax + Lyrica sedation",
    description:
      "BZ PAM with α2δ calcium-channel modulation increases CNS depression.",
    severity: "high",
  },
  {
    id: "oxycodone-pregabalin",
    drugIds: ["oxycodone", "pregabalin"],
    receptorIds: ["mu-opioid", "alpha2delta"],
    multiplier: 1.4,
    type: "risk",
    title: "Oxycodone + pregabalin",
    description:
      "μ agonism plus gabapentinoid — elevated sedation and respiratory risk.",
    severity: "high",
  },
  {
    id: "hydrocodone-zolpidem",
    drugIds: ["hydrocodone", "zolpidem"],
    receptorIds: ["mu-opioid", "gaba-a", "gaba-a-bz"],
    multiplier: 1.45,
    type: "risk",
    title: "Vicodin + Ambien",
    description:
      "Opioid + Z-drug: μ and α1-preferring GABA-A pathways stack CNS depression.",
    severity: "high",
  },
  {
    id: "diazepam-morphine",
    drugIds: ["diazepam", "morphine"],
    receptorIds: ["gaba-a", "gaba-a-bz", "mu-opioid"],
    multiplier: 1.5,
    type: "risk",
    title: "Sedative–opioid synergy",
    description:
      "Classic high-risk combination: enhanced CNS depression via GABA-A and μ-opioid pathways.",
    severity: "high",
  },
  {
    id: "alcohol-benzo",
    drugIds: ["ethanol", "alprazolam"],
    receptorIds: ["gaba-a", "gaba-a-bz", "nmda"],
    multiplier: 1.6,
    type: "risk",
    title: "Alcohol + benzodiazepine",
    description:
      "Ethanol and benzos both facilitate GABA-A and blunt NMDA. Strong synergistic intoxication and blackout risk.",
    severity: "high",
  },
  {
    id: "diazepam-ethanol",
    drugIds: ["diazepam", "ethanol"],
    receptorIds: ["gaba-a", "gaba-a-bz", "nmda"],
    multiplier: 1.6,
    type: "risk",
    title: "Valium + alcohol",
    description:
      "Diazepam BZ-site PAM with ethanol GABA/NMDA effects — classic high-risk pair.",
    severity: "high",
  },
  {
    id: "naloxone-opioid",
    drugIds: ["naloxone", "morphine"],
    receptorIds: ["mu-opioid"],
    multiplier: 0.15,
    type: "antagonistic",
    title: "Opioid receptor blockade",
    description:
      "Naloxone competitively occupies μ-opioid receptors and collapses morphine agonism (rescue antagonism).",
    severity: "info",
  },
  {
    id: "naloxone-oxycodone",
    drugIds: ["naloxone", "oxycodone"],
    receptorIds: ["mu-opioid"],
    multiplier: 0.15,
    type: "antagonistic",
    title: "Opioid receptor blockade",
    description:
      "Naloxone displaces oxycodone at μ receptors, rapidly reversing opioid effect.",
    severity: "info",
  },
  {
    id: "naloxone-buprenorphine",
    drugIds: ["naloxone", "buprenorphine"],
    receptorIds: ["mu-opioid"],
    multiplier: 0.45,
    type: "antagonistic",
    title: "Naloxone vs buprenorphine",
    description:
      "Naloxone can only partially displace very high-affinity buprenorphine; suboxone uses this PK/PD design orally.",
    severity: "info",
  },
  {
    id: "naltrexone-methadone",
    drugIds: ["naltrexone", "methadone"],
    receptorIds: ["mu-opioid"],
    multiplier: 0.12,
    type: "antagonistic",
    title: "Naltrexone blocks methadone",
    description:
      "Long-acting antagonist occupies μ receptors and abolishes methadone agonist tone.",
    severity: "info",
  },
  {
    id: "naltrexone-morphine",
    drugIds: ["naltrexone", "morphine"],
    receptorIds: ["mu-opioid"],
    multiplier: 0.12,
    type: "antagonistic",
    title: "Naltrexone blocks morphine",
    description: "Competitive μ blockade by naltrexone.",
    severity: "info",
  },
  {
    id: "caffeine-theophylline",
    drugIds: ["caffeine", "theophylline"],
    receptorIds: ["a1", "a2a"],
    multiplier: 1.4,
    type: "synergistic",
    title: "Methylxanthine stacking",
    description:
      "Both antagonize adenosine A₁/A₂A. Additive CNS stimulation and cardiac effects.",
    severity: "moderate",
  },
  {
    id: "propranolol-albuterol",
    drugIds: ["propranolol", "albuterol"],
    receptorIds: ["beta2", "beta1"],
    multiplier: 0.35,
    type: "antagonistic",
    title: "β-blockade of bronchodilation",
    description:
      "Non-selective β-blockade opposes β₂ agonism from albuterol, reducing bronchodilator efficacy.",
    severity: "high",
  },
  {
    id: "metoprolol-albuterol",
    drugIds: ["metoprolol", "albuterol"],
    receptorIds: ["beta1", "beta2"],
    multiplier: 0.7,
    type: "antagonistic",
    title: "Partial β-interaction",
    description:
      "Cardioselective β₁ blockade has less impact on β₂ than propranolol, but high doses can still blunt albuterol.",
    severity: "moderate",
  },
  {
    id: "ssri-nsaid",
    drugIds: ["sertraline", "ibuprofen"],
    receptorIds: ["cox1", "cox2", "sert"],
    multiplier: 1.1,
    type: "risk",
    title: "Bleeding risk (platelet + mucosa)",
    description:
      "SSRIs impair platelet serotonin; NSAIDs inhibit COX. Combined GI bleeding risk rises (not pure receptor synergy).",
    severity: "moderate",
  },
  {
    id: "aspirin-clopidogrel",
    drugIds: ["aspirin", "clopidogrel"],
    receptorIds: ["cox1", "p2y12"],
    multiplier: 1.35,
    type: "synergistic",
    title: "Dual antiplatelet therapy",
    description:
      "COX-1 irreversible inhibition + P2Y₁₂ blockade produce synergistic antiplatelet effect.",
    severity: "moderate",
  },
  {
    id: "warfarin-aspirin",
    drugIds: ["warfarin", "aspirin"],
    receptorIds: ["vkorc1", "cox1"],
    multiplier: 1.4,
    type: "risk",
    title: "Anticoagulant + antiplatelet",
    description:
      "VKORC1 inhibition plus platelet COX-1 blockade greatly elevates bleeding risk.",
    severity: "high",
  },
  {
    id: "lisinopril-spironolactone",
    drugIds: ["lisinopril", "spironolactone"],
    receptorIds: ["ace", "mr", "at1"],
    multiplier: 1.25,
    type: "synergistic",
    title: "RAAS dual blockade",
    description:
      "ACE inhibition plus mineralocorticoid receptor antagonism synergize on BP and potassium retention.",
    severity: "moderate",
  },
  {
    id: "losartan-lisinopril",
    drugIds: ["losartan", "lisinopril"],
    receptorIds: ["ace", "at1"],
    multiplier: 1.3,
    type: "synergistic",
    title: "ACEI + ARB stack",
    description:
      "Sequential RAAS blockade at ACE and AT₁. Additive BP effect with hyperkalemia risk.",
    severity: "moderate",
  },
  {
    id: "amphetamine-bupropion",
    drugIds: ["amphetamine", "bupropion"],
    receptorIds: ["dat", "net", "vmat2"],
    multiplier: 1.4,
    type: "risk",
    title: "Dopaminergic / noradrenergic stack",
    description:
      "Stimulant releaser + NDRI raise catecholamines via DAT/NET/VMAT2. Seizure and CV risk rise.",
    severity: "high",
  },
  {
    id: "lisdex-methylphenidate",
    drugIds: ["lisdexamfetamine", "methylphenidate"],
    receptorIds: ["dat", "net"],
    multiplier: 1.35,
    type: "risk",
    title: "Dual stimulant at DAT",
    description:
      "Releaser prodrug + reuptake inhibitor both engage DAT — additive catecholamine tone.",
    severity: "moderate",
  },
  {
    id: "methylphenidate-fluoxetine",
    drugIds: ["methylphenidate", "fluoxetine"],
    receptorIds: ["dat", "sert", "net"],
    multiplier: 1.2,
    type: "additive-plus",
    title: "Stimulant + SSRI",
    description:
      "Often co-prescribed; modest additive monoamine tone with CYP-mediated PK interactions possible.",
    severity: "info",
  },
  {
    id: "ketamine-benzo",
    drugIds: ["ketamine", "diazepam"],
    receptorIds: ["nmda", "gaba-a", "gaba-a-bz"],
    multiplier: 0.75,
    type: "antagonistic",
    title: "Benzodiazepine blunts ketamine psychotomimesis",
    description:
      "GABA-A positive modulation can dampen NMDA-antagonist dissociative intensity.",
    severity: "info",
  },
  {
    id: "ketamine-lorazepam",
    drugIds: ["ketamine", "lorazepam"],
    receptorIds: ["nmda", "gaba-a", "gaba-a-bz"],
    multiplier: 0.75,
    type: "antagonistic",
    title: "Ativan blunts ketamine effects",
    description:
      "Lorazepam GABA-A PAM can reduce dissociative/antidepressant intensity of ketamine.",
    severity: "info",
  },
  {
    id: "diphenhydramine-zolpidem",
    drugIds: ["diphenhydramine", "zolpidem"],
    receptorIds: ["h1", "gaba-a", "gaba-a-bz"],
    multiplier: 1.45,
    type: "risk",
    title: "Sedative stacking",
    description:
      "H₁ antagonism plus GABA-A α1-preferring modulation produce additive CNS depression.",
    severity: "moderate",
  },
  {
    id: "nicotine-varenicline",
    drugIds: ["nicotine", "varenicline"],
    receptorIds: ["nachr"],
    multiplier: 0.7,
    type: "antagonistic",
    title: "Partial vs full nAChR agonism",
    description:
      "Varenicline’s partial α4β2 agonism competes with nicotine’s full agonism at nAChR.",
    severity: "info",
  },
  {
    id: "nicotine-bupropion",
    drugIds: ["nicotine", "bupropion"],
    receptorIds: ["nachr", "dat", "net"],
    multiplier: 1.15,
    type: "additive-plus",
    title: "Nicotine + bupropion",
    description:
      "nAChR agonism with catecholamine reuptake inhibition used in smoking cessation pathways.",
    severity: "info",
  },
  {
    id: "thc-cbd",
    drugIds: ["thc", "cbd"],
    receptorIds: ["cb1", "cb2"],
    multiplier: 0.8,
    type: "antagonistic",
    title: "CBD modulates THC",
    description:
      "CBD can attenuate CB₁-mediated psychoactivity of THC while shifting peripheral tone.",
    severity: "info",
  },
  {
    id: "melatonin-zolpidem",
    drugIds: ["melatonin", "zolpidem"],
    receptorIds: ["mt1", "mt2", "gaba-a", "gaba-a-bz"],
    multiplier: 1.25,
    type: "synergistic",
    title: "Sleep pathway synergy",
    description:
      "MT₁/MT₂ agonism plus GABA-A positive modulation enhance sleep onset.",
    severity: "info",
  },
  {
    id: "sumatriptan-ssri",
    drugIds: ["sumatriptan", "sertraline"],
    receptorIds: ["5ht1b", "5ht1d", "sert"],
    multiplier: 1.2,
    type: "risk",
    title: "Triptan + SSRI serotonergic load",
    description:
      "5-HT₁B/₁D agonism with SERT inhibition elevates theoretical serotonin syndrome risk (clinical rate low).",
    severity: "moderate",
  },
  {
    id: "rizatriptan-sertraline",
    drugIds: ["rizatriptan", "sertraline"],
    receptorIds: ["5ht1b", "5ht1d", "sert"],
    multiplier: 1.2,
    type: "risk",
    title: "Maxalt + Zoloft",
    description: "Triptan + SSRI serotonergic combination.",
    severity: "moderate",
  },
  {
    id: "risperidone-fluoxetine",
    drugIds: ["risperidone", "fluoxetine"],
    receptorIds: ["d2", "5ht2a", "sert"],
    multiplier: 1.15,
    type: "additive-plus",
    title: "Antipsychotic + SSRI",
    description:
      "D₂/5-HT₂A antagonism with SERT inhibition; common in mood/psychotic spectra with PK interactions.",
    severity: "info",
  },
  {
    id: "aripiprazole-escitalopram",
    drugIds: ["aripiprazole", "escitalopram"],
    receptorIds: ["d2", "5ht1a", "sert"],
    multiplier: 1.1,
    type: "additive-plus",
    title: "Abilify + Lexapro",
    description:
      "D₂/5-HT₁A partial agonism with SERT inhibition — common depression augmentation pair.",
    severity: "info",
  },
  {
    id: "olanzapine-lorazepam",
    drugIds: ["olanzapine", "lorazepam"],
    receptorIds: ["h1", "m1", "gaba-a", "gaba-a-bz"],
    multiplier: 1.5,
    type: "risk",
    title: "Zyprexa + Ativan sedation",
    description:
      "Strong H₁/M₁ antagonism with benzo GABA-A PAM — heavy CNS depression.",
    severity: "high",
  },
  {
    id: "haloperidol-lorazepam",
    drugIds: ["haloperidol", "lorazepam"],
    receptorIds: ["d2", "gaba-a", "gaba-a-bz"],
    multiplier: 1.35,
    type: "synergistic",
    title: "Haldol + Ativan",
    description:
      "Classic acute agitation cocktail: D₂ blockade plus GABA-A positive modulation.",
    severity: "moderate",
  },
  {
    id: "metformin-semaglutide",
    drugIds: ["metformin", "semaglutide"],
    receptorIds: ["glp1r", "insulin-r"],
    multiplier: 1.3,
    type: "synergistic",
    title: "Glucose-lowering synergy",
    description:
      "GLP-1R agonism plus metformin’s AMPK/hepatic effects produce complementary glycemic control.",
    severity: "info",
  },
  {
    id: "amlodipine-metoprolol",
    drugIds: ["amlodipine", "metoprolol"],
    receptorIds: ["lt-type-ca", "beta1"],
    multiplier: 1.25,
    type: "synergistic",
    title: "Antihypertensive combination",
    description:
      "L-type Ca²⁺ blockade plus β₁ antagonism additively lower BP and heart rate demand.",
    severity: "info",
  },
  {
    id: "gabapentin-opioid",
    drugIds: ["gabapentin", "oxycodone"],
    receptorIds: ["alpha2delta", "mu-opioid"],
    multiplier: 1.35,
    type: "risk",
    title: "Gabapentinoid + opioid",
    description:
      "α2δ calcium-channel modulation plus μ agonism increases sedation and respiratory depression risk.",
    severity: "high",
  },
  {
    id: "pregabalin-morphine",
    drugIds: ["pregabalin", "morphine"],
    receptorIds: ["alpha2delta", "mu-opioid"],
    multiplier: 1.35,
    type: "risk",
    title: "Gabapentinoid + opioid",
    description:
      "Synergistic CNS depression via calcium-channel modulation and opioid pathways.",
    severity: "high",
  },
  {
    id: "clonidine-opioid",
    drugIds: ["clonidine", "morphine"],
    receptorIds: ["alpha2", "mu-opioid"],
    multiplier: 1.3,
    type: "synergistic",
    title: "α₂ + μ analgesia synergy",
    description:
      "α₂ agonism and μ-opioid agonism can synergize for analgesia and sedation.",
    severity: "moderate",
  },
  {
    id: "ondansetron-tramadol",
    drugIds: ["ondansetron", "tramadol"],
    receptorIds: ["5ht3", "sert", "mu-opioid"],
    multiplier: 0.85,
    type: "antagonistic",
    title: "5-HT₃ block may reduce tramadol analgesia",
    description:
      "Part of tramadol’s effect is serotonergic; 5-HT₃ antagonism can modestly blunt analgesia.",
    severity: "info",
  },
  {
    id: "donepezil-diphenhydramine",
    drugIds: ["donepezil", "diphenhydramine"],
    receptorIds: ["ache", "m1", "m2", "m3"],
    multiplier: 0.4,
    type: "antagonistic",
    title: "Anticholinergic vs AChE inhibitor",
    description:
      "Diphenhydramine’s muscarinic antagonism opposes cholinesterase-inhibitor benefits.",
    severity: "high",
  },
  {
    id: "sildenafil-nitrate-like-amlodipine",
    drugIds: ["sildenafil", "amlodipine"],
    receptorIds: ["pde5", "lt-type-ca"],
    multiplier: 1.2,
    type: "additive-plus",
    title: "Vasodilator combination",
    description:
      "PDE5 inhibition plus Ca-channel blockade can additively lower BP.",
    severity: "moderate",
  },
  {
    id: "fluoxetine-tramadol",
    drugIds: ["fluoxetine", "tramadol"],
    receptorIds: ["sert", "5ht1a", "mu-opioid"],
    multiplier: 1.5,
    type: "risk",
    title: "Serotonin toxicity risk",
    description:
      "Strong SERT inhibition with tramadol’s monoamine and weak opioid activity.",
    severity: "high",
  },
  {
    id: "venlafaxine-ibuprofen",
    drugIds: ["venlafaxine", "ibuprofen"],
    receptorIds: ["sert", "net", "cox1"],
    multiplier: 1.1,
    type: "risk",
    title: "SNRI + NSAID bleeding risk",
    description:
      "Platelet serotonergic effects plus COX inhibition raise bleeding potential.",
    severity: "moderate",
  },
  {
    id: "quetiapine-zolpidem",
    drugIds: ["quetiapine", "zolpidem"],
    receptorIds: ["h1", "gaba-a", "gaba-a-bz", "d2"],
    multiplier: 1.4,
    type: "risk",
    title: "Sedative antipsychotic + hypnotic",
    description:
      "H₁/D₂ antagonism with GABA-A modulation produces heavy sedation.",
    severity: "moderate",
  },
  {
    id: "codeine-fluoxetine",
    drugIds: ["codeine", "fluoxetine"],
    receptorIds: ["mu-opioid", "sert"],
    multiplier: 0.7,
    type: "antagonistic",
    title: "CYP2D6 inhibition reduces codeine activation",
    description:
      "Fluoxetine inhibits conversion of codeine → morphine, lowering μ activity (PK-mediated).",
    severity: "moderate",
  },
  {
    id: "atorvastatin-amlodipine",
    drugIds: ["atorvastatin", "amlodipine"],
    receptorIds: ["hmgcr", "lt-type-ca"],
    multiplier: 1.05,
    type: "additive-plus",
    title: "CV risk-factor combination",
    description:
      "Complementary lipid and BP targets commonly co-administered.",
    severity: "info",
  },
  {
    id: "pseudoephedrine-propranolol",
    drugIds: ["pseudoephedrine", "propranolol"],
    receptorIds: ["alpha1", "beta1", "beta2"],
    multiplier: 0.55,
    type: "antagonistic",
    title: "Decongestant vs β-blocker",
    description:
      "Indirect sympathomimetic activity is opposed by β-blockade; unopposed α effects possible.",
    severity: "moderate",
  },
  {
    id: "sertraline-bupropion",
    drugIds: ["sertraline", "bupropion"],
    receptorIds: ["sert", "dat", "net"],
    multiplier: 1.15,
    type: "additive-plus",
    title: "Zoloft + Wellbutrin",
    description:
      "SSRI + NDRI covers serotonin and catecholamine reuptake — common combination.",
    severity: "info",
  },
  {
    id: "sertraline-trazodone",
    drugIds: ["sertraline", "trazodone"],
    receptorIds: ["sert", "5ht2a", "h1"],
    multiplier: 1.15,
    type: "additive-plus",
    title: "SSRI + trazodone sleep aid",
    description:
      "Daytime SERT inhibition with nighttime 5-HT₂A/H₁ antagonism.",
    severity: "info",
  },
];

export function findActiveSynergies(selectedDrugIds: string[]): SynergyRule[] {
  const set = new Set(selectedDrugIds);
  return SYNERGIES.filter(
    (s) => set.has(s.drugIds[0]) && set.has(s.drugIds[1]),
  );
}
